### ISSUE TITLE
gaclib-website build error

### ISSUE THREAD

**Issue by hardfist** [vczh/WebsitePlayground#4]
![image](https://user-images.githubusercontent.com/8898718/64922859-783a4980-d806-11e9-8e13-8ca1526a0542.png)

使用yarn和lerna都会报该错

**Comment by hardfist** [comment]
神奇的是这个路径点进去是存在的

**Comment by hardfist** [comment]
查了下原因应该是webpack编译的时候，tsc的编译的webpac.js文件还没写入完成

**Comment by vczh** [comment]
这边关掉，搬去PR讨论
